from openpyxl import load_workbook # 파일 불러오기
import pyautogui

for x in range(2, 68): #범위 수정하기
    wb = load_workbook("Volumeloss.xlsx")
    ws = wb.active
    a = ws.cell(row=x, column=3).value
    print (a)
    print (x-1)
    b = str(a)
    pyautogui.click(-1332, 22, duration=0.5)
    pyautogui.click(-1710, 247, duration=0.5)
    pyautogui.write(b)

    pyautogui.moveTo(-1486, 293)
    pyautogui.mouseDown() # 마우스 버튼 누른 상태
    pyautogui.moveTo(-1438, 876)
    pyautogui.mouseUp() # 마우스 버튼 뗀 상태

    pyautogui.hotkey("ctrl", "c")

    pyautogui.click(-374, 21, duration=0.5)
    pyautogui.click(-364, 262, duration=0.5)
    pyautogui.sleep(0.1)
    pyautogui.hotkey("ctrl", "v")
    pyautogui.sleep(0.5)
    pyautogui.hotkey("ctrl")
    pyautogui.sleep(0.1)
    pyautogui.hotkey("v")

    pyautogui.click(-11, 982, duration=0.5)
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
    pyautogui.click()
